base:
  project: winequality-project
  random_state: 42
  target_col: TARGET


data_source:
  source: data_given/winequality.csv

### if you have data in db
db_info:
  ip: 138.85.180.211
  port: 3306
  username: ml
  password: ml123!
  database: ml_data
  table: raw_data

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
       alpha: 0.19
       l1_ratio: 0.01
#      alpha: 0.5
#      l1_ratio: 0.1
models:
  model_dir: saved_models
  model_path: saved_models/model.joblib

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: production_model

remote_server_details:
  hostname: <>
  username: <>
  password: <>
  remote_model_location: <>

mlflow_config:
  artifacts_dir: artifacts
  #experiment_name: ElasticNet Regression
  experiment_name: ElasticNetReg
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://127.0.0.1:1234